-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 01:14:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema app_web_pf_rossains
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `app_web_pf_rossains` ;

-- -----------------------------------------------------
-- Schema app_web_pf_rossains
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `app_web_pf_rossains` DEFAULT CHARACTER SET utf8 ;
USE `app_web_pf_rossains` ;

-- -----------------------------------------------------
-- Table `app_web_pf_rossains`.`alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_web_pf_rossains`.`alumno` ;

CREATE TABLE IF NOT EXISTS `app_web_pf_rossains`.`alumno` (
  `id_al_matricula` INT NOT NULL,
  `al_nombre` CHAR(16) NOT NULL,
  `al_paterno` CHAR(16) NOT NULL,
  `al_materno` CHAR(16) NULL DEFAULT NULL,
  `programa_educativo` ENUM('Licenciatura en Ciencias de la Computación', 'Licenciatura en Ingeniería en Ciencias de la Computación', 'Licenciatura en Ingeniería en Tecnologías de la Información') NOT NULL,
  PRIMARY KEY (`id_al_matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_web_pf_rossains`.`maestro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_web_pf_rossains`.`maestro` ;

CREATE TABLE IF NOT EXISTS `app_web_pf_rossains`.`maestro` (
  `id_ms_matricula` INT NOT NULL,
  `ms_nombre` CHAR(16) NOT NULL,
  `ms_paterno` CHAR(16) NOT NULL,
  `ms_materno` CHAR(16) NULL DEFAULT NULL,
  PRIMARY KEY (`id_ms_matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_web_pf_rossains`.`asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_web_pf_rossains`.`asignatura` ;

CREATE TABLE IF NOT EXISTS `app_web_pf_rossains`.`asignatura` (
  `id_asignatura` INT NOT NULL AUTO_INCREMENT,
  `asignatura` CHAR(45) NOT NULL,
  PRIMARY KEY (`id_asignatura`),
  UNIQUE INDEX `materia_UNIQUE` (`asignatura` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `app_web_pf_rossains`.`asesoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `app_web_pf_rossains`.`asesoria` ;

CREATE TABLE IF NOT EXISTS `app_web_pf_rossains`.`asesoria` (
  `id_asesoria` INT NOT NULL AUTO_INCREMENT,
  `fk_al_matricula` INT NOT NULL,
  `tiempo_asesoria_unix` BIGINT NOT NULL,
  `es_tu_maestro` TINYINT(1) NOT NULL,
  `estatus_comentario` CHAR(80) NULL DEFAULT NULL,
  `fk_asignatura` INT NOT NULL,
  `fk_ms_matricula` INT NOT NULL,
  `asunto_asesoria` CHAR(80) NOT NULL,
  `estatus` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_asesoria`),
  INDEX `fk_asesoria_alumno_idx` (`fk_al_matricula` ASC) VISIBLE,
  INDEX `fk_asesoria_maestro_idx` (`fk_ms_matricula` ASC) VISIBLE,
  INDEX `fk_asesoria_asignatura_idx` (`fk_asignatura` ASC) VISIBLE,
  CONSTRAINT `fk_asesoria_alumno`
    FOREIGN KEY (`fk_al_matricula`)
    REFERENCES `app_web_pf_rossains`.`alumno` (`id_al_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asesoria_maestro`
    FOREIGN KEY (`fk_ms_matricula`)
    REFERENCES `app_web_pf_rossains`.`maestro` (`id_ms_matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asesoria_asignatura`
    FOREIGN KEY (`fk_asignatura`)
    REFERENCES `app_web_pf_rossains`.`asignatura` (`id_asignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS client_ross;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'client_ross' IDENTIFIED BY 'client_ross';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `app_web_pf_rossains`.* TO 'client_ross';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `app_web_pf_rossains`.`alumno`
-- -----------------------------------------------------
START TRANSACTION;
USE `app_web_pf_rossains`;
INSERT INTO `app_web_pf_rossains`.`alumno` (`id_al_matricula`, `al_nombre`, `al_paterno`, `al_materno`, `programa_educativo`) VALUES (201336828, 'Vladimir', 'Andriyenko', NULL, '1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `app_web_pf_rossains`.`maestro`
-- -----------------------------------------------------
START TRANSACTION;
USE `app_web_pf_rossains`;
INSERT INTO `app_web_pf_rossains`.`maestro` (`id_ms_matricula`, `ms_nombre`, `ms_paterno`, `ms_materno`) VALUES (200000000, 'Rossainz', '................', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `app_web_pf_rossains`.`asignatura`
-- -----------------------------------------------------
START TRANSACTION;
USE `app_web_pf_rossains`;
INSERT INTO `app_web_pf_rossains`.`asignatura` (`id_asignatura`, `asignatura`) VALUES (1, 'Mineria de Datos Avanzada');

COMMIT;


-- -----------------------------------------------------
-- Data for table `app_web_pf_rossains`.`asesoria`
-- -----------------------------------------------------
START TRANSACTION;
USE `app_web_pf_rossains`;
INSERT INTO `app_web_pf_rossains`.`asesoria` (`id_asesoria`, `fk_al_matricula`, `tiempo_asesoria_unix`, `es_tu_maestro`, `estatus_comentario`, `fk_asignatura`, `fk_ms_matricula`, `asunto_asesoria`, `estatus`) VALUES (DEFAULT, 201336828, UNIX_TIMESTAMP('2019-04-05 16:00:00'), 1, 'jejej', 1, 200000000, 'Revision Preeliminar de Proyecyo Final', 1);
INSERT INTO `app_web_pf_rossains`.`asesoria` (`id_asesoria`, `fk_al_matricula`, `tiempo_asesoria_unix`, `es_tu_maestro`, `estatus_comentario`, `fk_asignatura`, `fk_ms_matricula`, `asunto_asesoria`, `estatus`) VALUES (DEFAULT, 201336828, UNIX_TIMESTAMP('2019-04-05 14:00:00'), 0, 'lol', 1, 200000000, 'Revision Final de Proyecto Final', 0);
INSERT INTO `app_web_pf_rossains`.`asesoria` (`id_asesoria`, `fk_al_matricula`, `tiempo_asesoria_unix`, `es_tu_maestro`, `estatus_comentario`, `fk_asignatura`, `fk_ms_matricula`, `asunto_asesoria`, `estatus`) VALUES (DEFAULT, 201336828, UNIX_TIMESTAMP('2019-03-06 16:20:00'), 0, NULL, 1, 200000000, 'Apollo con Maestria', NULL);

COMMIT;

USE `app_web_pf_rossains`;

DELIMITER $$

USE `app_web_pf_rossains`$$
DROP TRIGGER IF EXISTS `app_web_pf_rossains`.`asesoria_BEFORE_INSERT` $$
USE `app_web_pf_rossains`$$
CREATE DEFINER = CURRENT_USER TRIGGER `app_web_pf_rossains`.`asesoria_BEFORE_INSERT` BEFORE INSERT ON `asesoria` FOR EACH ROW
BEGIN
	IF(NEW.tiempo_asesoria_unix <= UNIX_TIMESTAMP(NOW())) THEN
		SET @aux :=  CONCAT('Este es un Trigger de consistencia, no puede agregar una asesoria en el pasado; unix_time: ',NEW.tiempo_asesoria_unix,' siendo las: ', UNIX_TIMESTAMP(NOW()));
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @aux;
	END IF;
END$$


USE `app_web_pf_rossains`$$
DROP TRIGGER IF EXISTS `app_web_pf_rossains`.`asesoria_BEFORE_DELETE` $$
USE `app_web_pf_rossains`$$
CREATE DEFINER = CURRENT_USER TRIGGER `app_web_pf_rossains`.`asesoria_BEFORE_DELETE` BEFORE DELETE ON `asesoria` FOR EACH ROW
BEGIN
	IF(OLD.tiempo_asesoria_unix <= UNIX_TIMESTAMP(NOW())) THEN
		SET @aux :=  CONCAT('Este es un Trigger de consistencia, no puede borrar una asesoria que ya paso; unix_time: ',OLD.tiempo_asesoria_unix,' siendo las: ', UNIX_TIMESTAMP(NOW()));
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = @aux;
	END IF;
END$$


DELIMITER ;
